// Generated by gencpp from file bev_package/service.msg
// DO NOT EDIT!


#ifndef BEV_PACKAGE_MESSAGE_SERVICE_H
#define BEV_PACKAGE_MESSAGE_SERVICE_H

#include <ros/service_traits.h>


#include <bev_package/serviceRequest.h>
#include <bev_package/serviceResponse.h>


namespace bev_package
{

struct service
{

typedef serviceRequest Request;
typedef serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct service
} // namespace bev_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bev_package::service > {
  static const char* value()
  {
    return "55d1a215f43fd1f64eb105a505b172c4";
  }

  static const char* value(const ::bev_package::service&) { return value(); }
};

template<>
struct DataType< ::bev_package::service > {
  static const char* value()
  {
    return "bev_package/service";
  }

  static const char* value(const ::bev_package::service&) { return value(); }
};


// service_traits::MD5Sum< ::bev_package::serviceRequest> should match
// service_traits::MD5Sum< ::bev_package::service >
template<>
struct MD5Sum< ::bev_package::serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bev_package::service >::value();
  }
  static const char* value(const ::bev_package::serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bev_package::serviceRequest> should match
// service_traits::DataType< ::bev_package::service >
template<>
struct DataType< ::bev_package::serviceRequest>
{
  static const char* value()
  {
    return DataType< ::bev_package::service >::value();
  }
  static const char* value(const ::bev_package::serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bev_package::serviceResponse> should match
// service_traits::MD5Sum< ::bev_package::service >
template<>
struct MD5Sum< ::bev_package::serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bev_package::service >::value();
  }
  static const char* value(const ::bev_package::serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bev_package::serviceResponse> should match
// service_traits::DataType< ::bev_package::service >
template<>
struct DataType< ::bev_package::serviceResponse>
{
  static const char* value()
  {
    return DataType< ::bev_package::service >::value();
  }
  static const char* value(const ::bev_package::serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEV_PACKAGE_MESSAGE_SERVICE_H
